AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Automatic Start or Stop Resources by Tag

Parameters:
  FunctionName:
    Description: Lambda function name
    Type: String
    Default: CosmosMonkey
  AutoStartStopTagKey:
    Description: Tag-key of resource to reference
    Type: String
    Default: AutoStartStop
  PollingSchedule:
    Description: Polling schedule literal of CloudWatch Event Rule
    Type: String
    Default: rate(5 minutes)
  LogRetensionInDays:
    Description: CloudWatch Logs retension in days for this function
    Type: Number
    Default: 7

Resources:
  FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${FunctionName}"
      RetentionInDays: !Ref LogRetensionInDays

  AutoStartStopFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      CodeUri: dist/
      Handler: main.handler
      Runtime: nodejs12.x
      Timeout: 900
      MemorySize: 256
      Role: !GetAtt AutoStartStopRole.Arn
      Environment:
        Variables:
          AUTO_START_STOP_TAG_KEY: !Ref AutoStartStopTagKey
          DRY_RUN: 'false'
      Events:
        Poller:
          Type: Schedule
          Properties:
            Schedule: !Ref PollingSchedule
      Policies:
        - Statement:
          # EC2 Instances
          - Effect: Allow
            Action:
              - ec2:DescribeInstances
              - ec2:StartInstances
              - ec2:StopInstances
            Resource: '*'
          # RDS Clusters, Instances
          - Effect: Allow
            Action:
              - rds:DescribeDBClusters
              - rds:DescribeDBInstances
              - rds:ListTagsForResource
              - rds:StartDBCluster
              - rds:StopDBCluster
              - rds:StartDBInstance
              - rds:StopDBInstance
            Resource: '*'
          # AutoScalingGroup
          - Effect: Allow
            Action:
              - autoscaling:DescribeAutoScalingGroups
              - autoscaling:UpdateAutoScalingGroup
            Resource: '*'

Outputs:
  AutoStartStopFunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt AutoStartStopFunction.Arn
