name: eslint

on:
  - pull_request

jobs:

  eslint:
    name: eslint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: install
        run: yarn install

      - name: type check
        run: yarn check

      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          eslint_flags: 'src/'
